### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by vincenzo-bullara** [nathan-b/rmse#1]
As far as I can tell your tool works wonderfully on windows as well, the only change necessary is to add the .exe extension to the file names in the get_rm_root method (rm_load.js).
![image](https://user-images.githubusercontent.com/76655832/219445332-5b8b484b-9d18-4298-8228-198f4081fc94.png)

I thought it might be good to let you know so you can maybe add this information to the readme.
Thanks for this useful tool.

**Comment by nathan-b** [comment]
Thank you so much for the information! I've pushed a change that should hopefully address this so it will work without modification.
